# Copyright 2025 River Vora
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Documentation
description: Report a problem with our documentation
labels: [ "a:documentation" ]
assignees: [ ]
body:
  - type: markdown
    attributes:
      value: |
        If you see a need for improvement to our documentation, make the issue here.

        If you found a clear typo, please open a PR with a fix instead of opening an issue.

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue type
      options:
        - Wrong or misleading information
        - Missing information
        - Styling or Accessibility
        - Typo (please open a PR instead)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Problem description
      description: |
        Please describe the problem as concisely as possible.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context (optional)
      description: |
        How has this issue affected you? What are you trying to accomplish?
        Providing context helps us come up with a solution that is most useful in the real world
    validations:
      required: false
  - type: input
    id: page
    attributes:
      label: Page with the problem
      description: Please, provide a link to the relevant documentation page
    validations:
      required: true
