# Copyright 2025 River Vora
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Feature request
description: Suggest an idea for this project
labels: [ "a:feature" ]
assignees: [ ]
body:
  - type: markdown
    attributes:
      value: |
        If you have a request or idea for a new feature, use this issue template.
        Provide a brief summary of the feature in the title above
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Tell us how it should work
    validations:
      required: true
  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior (optional)
      description: Explain the difference from current behavior
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Context
      description: |
        Why will this be useful? What will it require to be implemented?
    validations:
      required: true
